deltacat/compute/compactor/utils/io.py, deltacat/compute/stats/basic.py, deltacat/compute/stats/models/delta_stats_cache_result.py, deltacat/compute/stats/models/stats_completion_info.py, deltacat/compute/stats/models/stats_result.py, deltacat/compute/stats/types.py, deltacat/compute/stats/utils/io.py, deltacat/compute/stats/utils/stats_completion_file.py, deltacat/constants.py
When a compaction job run starts, the first things it needs are the (1) row count and (2) in-memory pyarrow table bytes for each new partition delta to be compacted. This change introduces an API to fetch these values given a range-set of partition delta stream positions.
=> Add delta stats collector functionality

deltacat/storage/interface.py, deltacat/storage/model/stream.py, deltacat/utils/ray_utils/concurrency.py
This PR changes existing APIs to inject `ray.remote` options providers when invoking storage APIs that will subsequently invoke concurrent Ray tasks for all blocks of a dataset.
=> [Storage] API Updates to add Ray Options Provider

deltacat/compute/metastats/model/stats_cluster_size_estimator.py, deltacat/io/aws/redshift/redshift_datasource.py, deltacat/io/dataset.py, deltacat/io/read_api.py
#28 
Tested via direct imports:
```
python
>>> import deltacat.io.aws.redshift.redshift_datasource
>>> import deltacat.io.dataset
>>> import deltacat.io.read_api
```
=> Update imports used for Ray Datasets / Ray 2.0+

.github/workflows/publish-to-pypi.yml
Echo tag step is throwing this error 
```
Run echo 0.1.11 >> $RELEASE_TAG
/home/runner/work/_temp/8[7](https://github.com/pfaraone/deltacat/actions/runs/3876493599/jobs/6610396785#step:9:8)564d[8](https://github.com/pfaraone/deltacat/actions/runs/3876493599/jobs/6610396785#step:9:9)8-5c28-4a45-843a-b33a4816a362.sh: line 1: $RELEASE_TAG: ambiguous redirect
Error: Process completed with exit code 1.
```
=> Hotfix: removed ambiguous redirect

.github/workflows/publish-to-pypi.yml, requirements.txt, setup.py
In #26  we pinned some dependency versions which pinned us to py38+ even though we've explicitly stated we are supporting py37 and above
=> Bumped dependencies down to support Python 3.7

deltacat/compute/compactor/steps/materialize.py
Tested on tables with delta entry files > 4000000 records.
Issue: https://github.com/ray-project/deltacat/issues/53
With `records_per_compacted_file = 4_000_000` (default):
```
Max in-memory byte size of any concatenated table groups: 8_188_431_980
Max record count of any concatenated table groups: 3_999_154
```
With `records_per_compacted_file = 20_000_000`:
```
Max in-memory byte size of any concatenated table groups: 13_510_287_893
Max record count of any concatenated table groups: 6_834_441
```
=> Eagerly materialize PyArrow tables up to records_per_compacted_file

deltacat/aws/s3u.py, deltacat/compute/compactor/compaction_session.py, deltacat/compute/compactor/steps/dedupe.py, deltacat/compute/compactor/steps/hash_bucket.py, deltacat/compute/compactor/steps/materialize.py, deltacat/compute/compactor/utils/primary_key_index.py, deltacat/compute/compactor/utils/system_columns.py, deltacat/constants.py
The actor RecordCountsPendingMaterialize takes up huge memory on a node. Moreover, it takes forever to process additional record counts after a certain threshold. This commit gets rid of the actor. A separate PR will introduce rebuilding primary key index that can be leveraged by the current compaction round. Also fixed the materialize to process dedupe results. Tested on two different tables.
=> Optimized the dedupe step and writing primary key index

deltacat/utils/pyarrow.py
Allow DeltaCAT implementations to specify a PyArrow table reader option to coerce int96 timestamps during Parquet reads.
Issue: #73
=> Add option to coerce int96 timestamp precision during Parquet reads

deltacat/compute/compactor/steps/dedupe.py, deltacat/compute/compactor/utils/system_columns.py, deltacat/utils/pyarrow.py
It has been observed that iterchunks() method of pyarrow sometimes returns unequal length chunks that leads to incorrect dedupe. This could cause record loss downstream.
=> Fix dedupe when iterchunks() doesn't return equal length chunks across columns

deltacat/logs.py
Issues: #55, #62 
Example log output taken from CloudWatch:
```
2023-02-15 06:15:13,435	INFO pid=1777 hash_bucket.py:170 -- (ray_runtime_context={'job_id': JobID(01000000), 'node_id': NodeID(93fe7173180d4b441a970c1a0a40c5c7f17d8870daa365e008cc5590), 'namespace': '3b627167-2f9f-4294-9696-785d43e2ffcb', 'task_id': TaskID(ed588515c5b6ec3bffffffffffffffffffffffff01000000), 'pg_id': None, 'assigned_resources': {'CPU': 1.0, 'node:172.31.35.247': 0.0001}}) -- Finished hash bucket task...
2023-02-15 06:16:08,111	INFO pid=1777 dedupe.py:168 -- (ray_runtime_context={'job_id': JobID(01000000), 'node_id': NodeID(93fe7173180d4b441a970c1a0a40c5c7f17d8870daa365e008cc5590), 'namespace': '3b627167-2f9f-4294-9696-785d43e2ffcb', 'task_id': TaskID(a816bd897febbb3fffffffffffffffffffffffff01000000), 'pg_id': …
```
=> Enhance logging observability with Ray Runtime Context and Process ID

deltacat/compute/compactor/compaction_session.py, deltacat/compute/compactor/steps/materialize.py
1. https://github.com/ray-project/deltacat/commit/3dfa2a430486a08fcb12bb7bb8bf9377ae469b11 introduced an unintentional `@ray.remote` annotation on `_execute_compaction_round` which has been removed in earlier commits. This function is called as a normal function and not as a Ray remote task, causing the compactor to break
2. `table.to_pandas(zero_copy_only=True)` doesn't offer any additional performance benefits - if zero copy is possible, it will attempt to do so regardless of this flag being present. With this flag enabled, it throws an exception if zero copy isn't possible and enforces strictness. This causes integration tests and compaction itself to break when source files need to be compacted to delimited text output files, and a conversion to Pandas DataFrames with multiple columns …
=> Hotfix: Remove @ray.remote annotation in compaction session and zero_copy_only in materialize

.github/workflows/ci.yml, .pre-commit-config.yaml, deltacat/compute/compactor/compaction_session.py
- The isort utility has dependency on 3.8+ (isort) - https://pypi.org/project/isort/ 
-  Flake8 6.0.0 is not compatible with 3.7
- [black linting compaction_session.py so lint job passes](https://github.com/ray-project/deltacat/pull/98/commits/fdaedf72c271c7b972664941da2971ec855c6736)
=> [ci][linting] Updated pre-commit repository mapping to be compatible with Python 3.7

deltacat/compute/compactor/compaction_session.py, deltacat/compute/compactor/steps/dedupe.py, deltacat/compute/compactor/steps/hash_bucket.py, deltacat/compute/compactor/steps/materialize.py, deltacat/utils/metrics.py
This PR adds support for emitting customized CloudWatch metrics.
Currently, it's main purpose is for runtime profiling and to detect stragglers during each step of compaction.
Closes: #57
=> [metrics] Add customized CloudWatch metrics support

deltacat/__init__.py, deltacat/compute/compactor/__init__.py, deltacat/compute/compactor/compaction_session.py, deltacat/compute/compactor/model/round_completion_info.py, deltacat/compute/compactor/steps/dedupe.py, deltacat/compute/compactor/utils/io.py
`PartitionLocator` is not hashable when using with dict as key. Revert it to string type. 
Remove un-used function parameters for compaction with no pki
=> Fix key type

deltacat/__init__.py, deltacat/compute/compactor/compaction_session.py, deltacat/compute/compactor/utils/io.py
All invocations of `_discover_deltas` will require the `equivalent_table_types` arg to be passed to disable resolving an appropriate table type. Earlier only one of the `_discover_deltas` had kwargs. Hence, the invocation that did not have this kwargs failed.
=> adding kwargs to all invocations of _discover_deltas

deltacat/compute/compactor/model/round_completion_info.py, deltacat/compute/compactor/utils/io.py
There are two fixes in this PR: 
a. TypeError when operator < is used between NoneType objects.
b. Deserialization of `HighWatermark` when reading round completion files.
=> fixing high watermark deserialization and TypeError

deltacat/compute/compactor/compaction_session.py, deltacat/compute/compactor/model/dedupe_result.py, deltacat/compute/compactor/model/hash_bucket_result.py, deltacat/compute/compactor/steps/dedupe.py, deltacat/compute/compactor/steps/hash_bucket.py, deltacat/compute/compactor/utils/io.py
This change adds logging for record counts and validates `# of hash bucket records - # of deduped records = # of materialized records`.
=> Add assertions to fast fail compaction in case of a metadata/execution issue

deltacat/compute/compactor/model/dedupe_result.py, deltacat/compute/compactor/model/hash_bucket_result.py, deltacat/compute/compactor/steps/dedupe.py, deltacat/compute/compactor/steps/hash_bucket.py
Update the hash bucket and dedupe result from dataclasses to tuple to mitigate some performance issues found during compaction on certain tables.
=> Update hash bucket and dedupe result dataclasses to tuple type

deltacat/compute/compactor/repartition_session.py, deltacat/compute/compactor/utils/round_completion_file.py
Repartition only needs to know the source and destination. This pr removes the dependency on rebase_source_partition and simplifies the delta discovery by directly scanning the compacted table, either ray or spark.
```
If repartition_during_rebase:
use spark variant
else:
use ray variant
```
Related issue: https://github.com/ray-project/deltacat/issues/133
=> remove dependency on rebase_source_partition

deltacat/compute/compactor/compaction_session.py, deltacat/compute/compactor/model/compaction_session_audit_info.py, deltacat/compute/compactor/model/dedupe_result.py, deltacat/compute/compactor/model/hash_bucket_result.py, deltacat/compute/compactor/model/materialize_result.py, deltacat/compute/compactor/model/round_completion_info.py, deltacat/compute/compactor/steps/dedupe.py, deltacat/compute/compactor/steps/hash_bucket.py, deltacat/compute/compactor/steps/materialize.py, deltacat/compute/compactor/utils/io.py, deltacat/compute/compactor/utils/round_completion_file.py, deltacat/storage/model/delta.py, deltacat/tests/compactor/utils/test_io.py, deltacat/tests/utils/test_resources.py, deltacat/utils/ray_utils/concurrency.py, deltacat/utils/resources.py
[Description] It is important to capture audit automatically and analyze the datapoints from significant number of runs to recognize a pattern and come up with a formula to predict resource consumption. This would improve reliability and efficiency.
[Motivation] #141 
Example Audit Info:
```
"compactionAudit": {
"deltacatVersion": "0.1.18b1",
"clusterCpu": 3658,
"deltaDiscoveryTimeInSeconds": 2.710052251815796,
"inputFileCount": 31750,
"inputSizeBytes": 5234658392405,
"totalClusterMemoryBytes": 42087227851116,
"hashBucketCount": 385,
"hashBucketTimeInSeconds": 111.62457704544067,
"totalClusterObjectStoreMemoryBytes": 23050000000000,
"objectStoreMemoryUsedBytesByHashBucketing": 1719833215762,
"inputRecords": 61183765994,
"peakMemoryUsedBytesByHashBucketing": 1595277312, …
```
=> Capturing all the performance metrics in an audit

deltacat/compute/compactor/model/delta_file_envelope.py, deltacat/compute/compactor/model/delta_file_locator.py, deltacat/compute/compactor/steps/dedupe.py, deltacat/compute/compactor/steps/hash_bucket.py, deltacat/compute/compactor/steps/materialize.py, deltacat/compute/compactor/utils/system_columns.py
This PR adds support for skipping download cold manifest entries during materialize step.
To achieve this, we add row count of downloaded manifest entries from hash bucket step and carry over to materialize step. Before actually downloading manifest entries in materialize, we check if the row count equals to dedupped row count first. When row count matches, we simply copy the manifest entry by reference.
=> [skip download cold manifest] Add support for skipping download cold manifest entries during materialize step

deltacat/compute/compactor/compaction_session.py, deltacat/compute/compactor/steps/materialize.py
This PR adds support for 1. Disable manifest entry copy by reference for special compaction use cases 2. Correct PyarrowWriteResult when using referenced manifest entry metadata.
Testing:
1. Tested disable copy by reference by passing a rebase_source_partition_locator.
2. Tested copy by reference in normal incremental compaction case.
=> [skip untouched files]Disable copy by reference during backfill and rebase only compaction; Fix referenced manifest PyarrowWriteResult

deltacat/__init__.py, deltacat/compute/compactor/compaction_session.py, deltacat/compute/compactor/utils/round_completion_file.py
This will allow us to override the s3 client kwargs and hence execute S3 upload on behalf of the user that runs the `compact_partition`.
=> Allow s3 client kwargs as argument of compact_partition

deltacat/__init__.py, deltacat/compute/compactor/compaction_session.py, deltacat/compute/compactor/repartition_session.py
Allows S3 keyword arguments to be passed into repartition session for use cases such as AWS credential overrides.
=> Allow s3_client_kwargs to be passed into repartition

deltacat/__init__.py, deltacat/compute/compactor/compaction_session.py
Setting default value in parent scope to avoid unpacking None type values.
=> Move s3_client_kwargs default setter to parent scope

deltacat/compute/compactor/steps/repartition.py, deltacat/tests/test_repartition.py
Fixed Issue 1: a new dw_last_update_int64 column is added for filtering, but need to be dropped 
Fixed issue 2: dw_last_update could have null value, avoid dropping it during filtering
=> keep null row and remove dw_int64 column

deltacat/aws/s3u.py, deltacat/exceptions.py, deltacat/storage/model/types.py, deltacat/types/media.py, deltacat/types/tables.py, deltacat/utils/pyarrow.py, requirements.txt, setup.py
[Motivation] #162
Testing
-----
```python
delta_result = DS.list_deltas(namespace=namespace, 
...                         table_name=table_name, 
...                         partition_values=ordered_partition_values, 
...                         table_version=table_version, 
...                         include_manifest=True,
...                         equivalent_table_types=[])
delta = delta_result.read_page()[0]
table = DS.download_delta_manifest_entry(delta, 0, TableType.PYARROW_PARQUET)
```
=> Adding support for reading table into ParquetFile

benchmark-requirements.txt, deltacat/benchmarking/README.md, deltacat/benchmarking/benchmark_parquet_reads.py, deltacat/benchmarking/conftest.py, dev-requirements.txt
This PR adds in `pytest-benchmark` harnesses for benchmarking DeltaCat's Parquet reads across different possible solutions.
The various axes being benchmarked in this PR:
1. `read_fn` is the function used to read the Parquet file (DeltaCat vs PyArrow vs Daft Table)
2. We use publicly-available Parquet files hosted in AWS S3, where different files have different data distributions/profiles
3. We also benchmark single-column-reads vs all-column-reads
```
pytest deltacat/benchmarking/benchmark_parquet_reads.py --benchmark-only --benchmark-group-by=group,param:name
```
The above will output a benchmarking report, comparing the performance of various functions which perform a Parquet file read into an Arrow table.
=> Add pytest benchmarking for Parquet reads

deltacat/aws/clients.py, deltacat/tests/aws/test_clients.py, dev-requirements.txt
This change adds a function that calls the instance metadata service endpoint with retry logic. The function - `block_until_instance_metadata_service_returns_success` - blocks until the endpoint is available or the maximum number of retries is exceeded. The function is used in _get_session_from_kwargs to block boto3 session creation until the instance profile IAM role is available.
=> Polling EC2 Instance Metadata endpoint until HTTP 200 OK

.github/workflows/publish-to-pypi.yml
Editing and creating a release should now trigger the Publish Python distributions to PyPI workflow. Previously, a new release *and* tag had to be created to trigger the workflow
=> Trigger a "Publish Python distributions to PyPI" GH Actions workflow on additional event types

deltacat/aws/redshift/model/manifest.py, deltacat/aws/s3u.py, deltacat/compute/compactor/compaction_session.py, deltacat/compute/compactor/model/compact_partition_params.py, deltacat/compute/compactor/model/compaction_session_audit_info.py, deltacat/compute/compactor/model/delta_annotated.py, deltacat/compute/compactor/model/delta_file_envelope.py, deltacat/compute/compactor/model/round_completion_info.py, deltacat/compute/compactor/utils/io.py, deltacat/compute/compactor/utils/sort_key.py, deltacat/compute/compactor_v2/compaction_session.py, deltacat/compute/compactor_v2/constants.py, deltacat/compute/compactor_v2/model/hash_bucket_result.py, deltacat/compute/compactor_v2/model/merge_input.py, deltacat/compute/compactor_v2/steps/hash_bucket.py, deltacat/compute/compactor_v2/utils/io.py, deltacat/compute/compactor_v2/utils/primary_key_index.py, deltacat/compute/compactor_v2/utils/task_options.py, deltacat/logs.py, deltacat/tests/compute/compactor/test_compact_partition_params.py, deltacat/tests/compute/compactor_v2/steps/test_hash_bucket.py, deltacat/tests/utils/test_resources.py, deltacat/types/partial_download.py, deltacat/utils/pyarrow.py, deltacat/utils/ray_utils/concurrency.py, deltacat/utils/resources.py, requirements.txt
=> Compaction session implementation for algo v2

.github/workflows/publish-to-pypi.yml
#186 
This commit fixes the issue when using `moto` to run unit tests as it is only defined in `dev-requirements.txt`.
=> Install dev-dependencies before running tests

deltacat/aws/clients.py, deltacat/compute/compactor/model/compact_partition_params.py, deltacat/compute/compactor/model/compaction_session_audit_info.py, deltacat/compute/compactor/model/delta_annotated.py, deltacat/compute/compactor_v2/compaction_session.py, deltacat/compute/compactor_v2/constants.py, deltacat/compute/compactor_v2/steps/hash_bucket.py, deltacat/compute/compactor_v2/utils/content_type_params.py, deltacat/compute/compactor_v2/utils/task_options.py, deltacat/io/memcached_object_store.py, deltacat/tests/utils/test_resources.py, deltacat/utils/resources.py
=> Capture memory gb seconds and bug fixes

deltacat/__init__.py, requirements.txt, setup.py
* Updates the daft version to 0.1.16 which switches daft over to use OpenSSL over Rustls
* Also includes correct behavior when parsing a parquet schema with int96 options which the `ARROW_SCHEMA` field is also set
=> update daft to 0.1.16 that uses openssl and correct arrow schema parsing with int96 options

deltacat/__init__.py
- Can't use compatible minor versions (`deltacat ~= 0.1`) for pre-releases (like 0.1.18b19)
=> Version Bump to 0.1.19 (non-prerelease)

deltacat/compute/compactor_v2/constants.py, deltacat/io/memcached_object_store.py
#150 
It is a best practice to set the connect timeout and timeout parameters for socket. Otherwise the connection can hang making the recovery very difficult leading to job wasting resources. This commit aims to set these parameters based on our requirement, and retry on `TimeoutError` to recover from transient connection timeouts.
=> Setting connect timeout and timeout parameters

deltacat/compute/compactor/compaction_session.py, deltacat/compute/compactor/model/compaction_session_audit_info.py, deltacat/compute/compactor/model/compactor_version.py, deltacat/compute/compactor/model/round_completion_info.py, deltacat/compute/compactor_v2/compaction_session.py
#150 
This commit adds the compactor version in round completion file and audit to allow looking up what version was used and also allows driver to programmatically lookup version to decide whether to run rebase or incremental compaction. E.g., if version changes, a rebase has to be run.
=> Adding compactor version in audit info and rci

deltacat/compute/compactor_v2/utils/dedupe.py, deltacat/compute/compactor_v2/utils/task_options.py, deltacat/utils/ray_utils/concurrency.py
=> Add index array size to estimation, fix dedupe and concurrency

deltacat/__init__.py, deltacat/aws/constants.py, deltacat/tests/utils/test_daft.py, deltacat/utils/daft.py, deltacat/utils/pyarrow.py, deltacat/utils/schema.py, requirements.txt, setup.py
* Lowers peak memory utilization by 50%
* Introduces eager memory cleanup in jemalloc memory allocator, reducing resting memory utilization
* Speeds up "all-column" reads by 48%
* Adds max connection limit of 8 per file
* Produce an Arrow chunked table directly to work around any schema-related issues when interoperating with PyArrow
These changes come with an API change, where Daft now provides a `read_parquet_into_pyarrow` function which returns a chunked PyArrow table directly. This PR introduces changes to use this new API as well.
Daft PRs that added these improvements:
* Adds API to read directly into a PyArrow table: https://github.com/Eventual-Inc/Daft/pull/1366
* Optimize parquet page reading with streams: https://github.com/Eventual-Inc/Daft/pull/1365
* Add Configurable thread …
=> Upgrade Daft to 0.1.17 for improved performance and resource usage

deltacat/tests/utils/test_pyarrow.py, deltacat/utils/pyarrow.py, deltacat/utils/schema.py
This PR shares `coerce_pyarrow_table_to_schema` across `pyarrow.py` and `daft.py` utility files
This utility will apply a provided schema (`input_schema`) to a table that is read from a file. This application has the following properties, as documented in the function docstring:
```
1. For each field in `pa_table`, cast it to the field in `input_schema` if one with a matching name
is available
2. Reorder the fields in the casted table to the supplied schema, dropping any fields in `pa_table`
that do not exist in the supplied schema
3. If any fields in the supplied schema are not present, add a null array of the correct type
```
Note that this is a departure from the current behavior in `pyarrow.py`, which leverages the `_get_compatible_target_schema` function (removed in this PR) and only …
=> Use `coerce_pyarrow_table_to_schema` in pyarrow download

deltacat/__init__.py, deltacat/utils/metrics.py
The current implementation explicitly sets metric dimensions and namespace. These configurations are not necessarily desired by everybody, and thus should be derived from the passed-in metrics_config object instead. 
This change will "break" existing metrics, thus necessitating a minor package version bump.
Testing
- Changes were deployed locally and tested to ensure that both passing in and omitting namespace and dimensions worked properly
=> Derive optional metric configurations from metrics_config

deltacat/compute/compactor/model/round_completion_info.py, deltacat/compute/compactor_v2/compaction_session.py, deltacat/compute/compactor_v2/steps/merge.py, deltacat/tests/compute/compactor_v2/test_hashlib.py, deltacat/tests/utils/test_resources.py, deltacat/utils/pyarrow.py, deltacat/utils/resources.py
#150 
As part of this commit, we will persist input inflation and input average record sizes in round completion file. This will allow us to use it to infer sizes of upcoming incremental deltas. Though we have sizes of compacted, we don't have sizes for incremental delta. Hence, this approach has been found to provide most accurate figures instead of parquet uncompressed size in the parquet metadata. Moreover, this solution is generic and applies to any content type.
=> Persisting previous delta inflation and avg record sizes

deltacat/__init__.py
#150 
This commit only has a version bump. We bump up the version because the previous version 0.2.0 was already used.
=> 0.2.0 file name has already been used, hence bumping up the version

deltacat/__init__.py, deltacat/compute/compactor_v2/utils/primary_key_index.py, deltacat/io/memcached_object_store.py, deltacat/io/object_store.py
#150 
This commit simplifies the hasher initialization. This also introduces a new method using which we can close all active connections to the object store. This method is particularly helpful whether we are done with the `object_store` object.
=> Simplify the hash initialization in the memcached object store

deltacat/aws/clients.py, deltacat/tests/aws/test_clients.py
The first call to `_get_url` may fail and raise an exception that is not caught by tenacity's retries.
=> Fix EC2 instance metadata queries not getting caught by the retry handler

deltacat/utils/metrics.py, requirements.txt, setup.py
CloudWatch Embedded Metric Format (EMF) allows for emitting metrics through logs. Using the `aws_embedded_metrics` library, the CloudWatch agent is leveraged to emit EMF logs. This PR adds this metrics option to deltacat.
Testing
- Tested locally by varying/omitting each field
=> Add functionality for emitting metrics through CloudWatch EMF

deltacat/compute/compactor/utils/io.py, deltacat/compute/compactor_v2/utils/io.py, deltacat/tests/compute/compactor_v2/steps/test_merge.py, deltacat/tests/compute/compactor_v2/test_compaction_session.py, deltacat/tests/test_utils/pyarrow.py
#150 
This commit aims to gracefully handle the case when there are not input deltas to compact. The added test case ensures that calling compact_partition when there are no new deltas to compact just returns `None`, in other words, is a NoOp.
=> Gracefully handle case where no new input deltas to compact

deltacat/compute/compactor/model/compaction_session_audit_info.py, deltacat/compute/compactor/model/round_completion_info.py, deltacat/compute/compactor_v2/compaction_session.py, deltacat/tests/compute/test_compact_partition_incremental.py, deltacat/tests/compute/test_compact_partition_rebase_then_incremental.py, deltacat/tests/compute/test_util_common.py, deltacat/tests/compute/test_util_create_table_deltas_repo.py
Currently, we were setting audit after uploading all the args. For incremental cases, this will only set the size of the incremental delta instead of total size of input. This PR fixes this issue.
=> Upload audit to s3 after setting all args

deltacat/compute/compactor/compaction_session.py, deltacat/compute/compactor/model/compaction_session_audit_info.py, deltacat/compute/compactor_v2/compaction_session.py
`ClusterUtilizationOverTimeRange` provides misleading behavior when used within deltacat. This is because it estimates cluster-level resource usage rather than partition-specific usage. As a result, it's better to use `ClusterUtilizationOverTimeRange` from within the driver class that calls deltacat functions.
Testing:
- Tested on personal stack
=> Remove cluster_util from deltacat

.github/workflows/ci.yml, .github/workflows/publish-to-pypi.yml, deltacat/tests/compute/test_compact_partition_incremental.py, deltacat/tests/compute/test_compact_partition_rebase_then_incremental.py
This PR adds performance regression checks for the compactor.
Examples:
- PR Alert Comment
-   https://github.com/rkenmi/deltacat/commit/e3aec476d16fcf12de43efe3b906c5181545ba9d#comments
- Workflow Job Summary
-  https://github.com/rkenmi/deltacat/actions/runs/7012495401
=> Add compactor performance regression checks within Github Workflows

requirements.txt, setup.py
Bumping daft to include fix issue when reading empty parquet files with daft
```
pyarrow.lib.ArrowInvalid: cannot construct ChunkedArray from empty vector and omitted type
```
And when parquet page header is really big
```
ValueError: DaftError::ArrowError External format error: Operation would exceed memory use threshold
```
=> Bump daft to 0.2.4

deltacat/aws/s3u.py, deltacat/compute/compactor/compaction_session.py, deltacat/compute/compactor/steps/dedupe.py, deltacat/compute/compactor/steps/hash_bucket.py, deltacat/compute/compactor/steps/materialize.py, deltacat/compute/compactor_v2/compaction_session.py, deltacat/compute/compactor_v2/steps/hash_bucket.py, deltacat/compute/compactor_v2/steps/merge.py, deltacat/tests/utils/test_resources.py, deltacat/utils/daft.py, deltacat/utils/resources.py
This change adds critical low-level debugging logs, most importantly node-level memory utilization. This change will help greatly in catching OOM failures that otherwise go undetected.
Testing:
- Tested on local stack
=> Add low-level debugging

deltacat/compute/compactor_v2/compaction_session.py, deltacat/compute/compactor_v2/model/hash_bucket_input.py, deltacat/compute/compactor_v2/steps/hash_bucket.py, deltacat/compute/compactor_v2/steps/merge.py, deltacat/compute/compactor_v2/utils/task_options.py
Add the task index into the hb and merge logs. This makes which tasks have started/ended clearer while also logging the hb task index, which was not logged before.
=> Add task index into logs for hb and merge

deltacat/compute/compactor_v2/utils/task_options.py
The existing memory allocation logic does not account for several unexpected inefficiencies. 
These inefficiencies are:
1. When converting the pyarrow table to numpy, the process memory usage is doubling, indicating that pyarrow is not performing a zero-copy conversion like we expected. To account for this, we add the pk_size_bytes attribute again.
2. When generating sha1 hashes using hashlib, the memory inefficiencies of the library accumulate for tables with large numbers of primary keys. To account for this, we add num_rows * 20 again.
Testing:
- These changes were tested by running on personal stack and verifying the memory allocation limit was increased.
=> Increase memory allocation calculation based on missed memory inefficiencies

deltacat/aws/s3u.py, deltacat/catalog/default_catalog_impl/__init__.py, deltacat/compute/merge_on_read/__init__.py, deltacat/compute/merge_on_read/daft.py, deltacat/compute/merge_on_read/model/merge_on_read_params.py, deltacat/compute/merge_on_read/utils/delta.py, deltacat/storage/interface.py, deltacat/storage/model/types.py, deltacat/tests/catalog/data/sample_table.csv, deltacat/tests/catalog/test_default_catalog_impl.py, deltacat/tests/compute/test_compact_partition_incremental.py, deltacat/tests/compute/test_compact_partition_rebase_then_incremental.py, deltacat/tests/local_deltacat_storage/README.md, deltacat/tests/local_deltacat_storage/__init__.py, deltacat/tests/test_utils/pyarrow.py, deltacat/tests/utils/test_daft.py, deltacat/types/media.py, deltacat/types/tables.py, deltacat/utils/daft.py, requirements.txt, setup.py
```
from deltacat.catalog import default_catalog_impl as dc
dc.initialize(ds=ds)
df = dc.read_table(
table=TABLE_NAME,
namespace=self.TABLE_NAMESPACE,
catalog=self.LOCAL_CATALOG_NAME,
distributed_dataset_type=DistributedDatasetType.DAFT,
merge_on_read=False,
deltacat_storage_kwargs=self.kwargs,
)
df.show()
```
Part of #265
=> Initial draft of Daft dataframe support for DeltaCAT catalog

deltacat/compute/compactor_v2/compaction_session.py, deltacat/compute/compactor_v2/model/merge_file_group.py, deltacat/compute/compactor_v2/model/merge_input.py, deltacat/compute/compactor_v2/model/merge_result.py, deltacat/compute/compactor_v2/steps/hash_bucket.py, deltacat/compute/compactor_v2/steps/merge.py, deltacat/compute/compactor_v2/utils/delta.py, deltacat/compute/compactor_v2/utils/merge.py, deltacat/tests/compute/compact_partition_test_cases.py, deltacat/tests/compute/compactor_v2/steps/test_merge.py
This PR adds a feature to skip hash bucketing if the user-supplied hash bucket count is set to 1.
Changes
- If hash bucket count is set to 1, delta file envelopes are loaded into the `merge` step directly to compact tables
- Since the `merge` step could be dealing with delta file envelope object refs (remote) or pure delta file envelopes (local), an abstraction layer is added for delta file envelope retrieval during invoke by `merge`.
Initial Benchmarks
Input Delta Size | Default Run 1 (secs) | Default Run 2 (secs) | Default Run 3 (secs) | Default Avg. (secs) | Skip HB Run 1 (secs) | Skip HB Run 2 (secs) | Skip HB Run 3 (secs) | Skip HB Avg. (secs) | Skip HB % Improvement
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
1.2 GB | 196.80 | 194.44 | 194.91 | 195.38 | 80.54 | 79.88 | 78.95 | …
=> Skip hash bucketing for small partitions

deltacat/utils/daft.py
* Pass AWS region into Daft `IOConfig` which will allow daft to avoid hitting the local IMDS.
* Hitting the IMDS server under load has yielded errors such as `hyper::Error(Connect, ConnectError("dns error", Custom { kind: Uncategorized, error: "failed to lookup address information: Temporary failure in name resolution" }))`
* However to skip IMDS, we have to use a version of daft that was build after this merged https://github.com/Eventual-Inc/Daft/pull/1886 which should be `getdaft== 0.2.15`
* I will make a follow on PR that upgrades daft to this version as well
=> Pass region into daft io-config to prevent s3 client hitting imds

deltacat/aws/clients.py
This change fixes the IMDS health check for IMDSv2 backed EC2 instances, before generating a AWS session.
=> Add wait support for IMDSv2

deltacat/compute/compactor/model/compact_partition_params.py, deltacat/compute/compactor_v2/compaction_session.py, deltacat/compute/compactor_v2/model/hash_bucket_input.py, deltacat/compute/compactor_v2/model/merge_input.py, deltacat/compute/compactor_v2/steps/hash_bucket.py, deltacat/compute/compactor_v2/steps/merge.py, deltacat/compute/compactor_v2/utils/task_options.py, deltacat/logs.py, deltacat/tests/compute/test_compact_partition_params.py
This change adds the `memory_logs_enabled` param. When set to true, low-level debug logs related to memory usage will be enabled. By using this param, we can avoid unnecessary logs on tables that do not require special attention to memory usage.
Testing:
- tested on personal stack
=> Add memory_logs_enabled param

deltacat/compute/compactor/model/compact_partition_params.py, deltacat/compute/compactor_v2/compaction_session.py, deltacat/compute/compactor_v2/model/hash_bucket_input.py, deltacat/compute/compactor_v2/model/merge_input.py, deltacat/compute/compactor_v2/steps/hash_bucket.py, deltacat/compute/compactor_v2/steps/merge.py, deltacat/compute/compactor_v2/utils/task_options.py, deltacat/logs.py, deltacat/tests/compute/test_compact_partition_params.py, deltacat/utils/resources.py
This change provides resource estimates for input deltas during local merge, so that Ray can schedule tasks responsibly when there are many concurrent jobs. It also addresses a bug where in some instances, `ray.available_resources()` may not yet report anything, causing the ClusterUtilization to throw exceptions during resource calculation and fail jobs prematurely.
=> Provide resource estimates for local merge

deltacat/compute/compactor/model/compaction_session_audit_info.py, deltacat/compute/compactor_v2/compaction_session.py, deltacat/compute/compactor_v2/steps/merge.py
- With the changes in compactor v2 delete algorithm introduced in https://github.com/ray-project/deltacat/pull/280, the total number of records dropped is now returned from the `merge` step. This should be audit logged like record deduped (`recordsDeduped`)
=> Audit logging records deleted (`recordsDeleted`)

deltacat/aws/constants.py, deltacat/aws/s3u.py, deltacat/compute/compactor_v2/compaction_session.py, deltacat/compute/compactor_v2/constants.py, deltacat/compute/compactor_v2/deletes/utils.py, deltacat/compute/compactor_v2/steps/hash_bucket.py, deltacat/compute/compactor_v2/steps/merge.py, deltacat/compute/compactor_v2/utils/io.py, deltacat/compute/compactor_v2/utils/merge.py, deltacat/tests/utils/test_metrics.py, deltacat/utils/metrics.py
This commit adds low level metrics to deltacat. Below are the metrics covered as part of this PR:
- Download (latency, failure, success)
- Upload (latency, failure, success)
- Hash bucket (latency, failure, success)
- Merge (latency, failure, success)
- Prepare Deletes (latency, failure, success)
- Discover Deltas (latency, failure, success)
- Materialize (latency, failure, success)
Observed an overhead of 0.02s when actor is not yet available on the node and 0.009s when actor is already available.
=> Instrumenting granular metrics to understand the RCA quickly

deltacat/__init__.py, deltacat/compute/compactor_v2/compaction_session.py, deltacat/tests/utils/test_metrics.py, deltacat/utils/metrics.py
When there are too many metrics being emitted, actor dies due to a very high load it gets. This commit will aim to use a separate feature that allows us to configure metrics while not using actors.
=> Use class cache instead of ray actor as a more scalable approach

deltacat/__init__.py, deltacat/compute/compactor_v2/utils/task_options.py, deltacat/utils/daft.py, requirements.txt, setup.py
* Upgrade Daft to 0.2.23
* Cut down connect timeout to 5 seconds and read timeout to 10 seconds
* Add Daft Transient error to retry list for ray
* This version of daft also will not panic on connection issues.
=> Leverage Daft Transient Errors to retry tasks on ray and drop timeout times

deltacat/__init__.py, deltacat/compute/compactor_v2/utils/task_options.py
With Ray version 2.20.0, the scheduling strategy does not scale up to full utilization due the algorithm mentioned in https://docs.ray.io/en/latest/ray-core/scheduling/index.html for default strategy. We were seeing Ray only spinning up nodes to handle just 20% of tasks in queue. With this change we will be using SPREAD strategy which will proactively spin up nodes to handle all of the load in queue. Especially for merge tasks, SPREAD is the ideal strategy because we do not care about node locality. 
NOTE: Existing tests are exercised.
=> Fix compaction jobs latency increase due to changes in scheduling algo in ray 2.20.0

deltacat/aws/constants.py, deltacat/aws/s3u.py, deltacat/compute/compactor_v2/utils/task_options.py, deltacat/tests/aws/test_s3u.py
New transient exceptions (e.g. SSL handshake errors) were discovered from stress tests, which were incorrectly classified as non-retryable errors.
=> Additional retryable exceptions for s3 put/get

deltacat/compute/compactor_v2/constants.py, deltacat/compute/compactor_v2/steps/hash_bucket.py, deltacat/compute/compactor_v2/steps/merge.py, deltacat/tests/utils/test_resources.py, deltacat/utils/resources.py
We are seeing a resource leak from daft `read_parquet` which halts processing and times out the whole job. However, although this issue is very hard to reproduce in a normal circumstances, it is quite prevalent in production. Hence, a symptomatic fix will be quite useful to avoid entire job failures. We can fail just the task timing out and let ray retry it on a different node. However, today ray remote call does not support timeout argument so we cannot directly timeout a task (https://github.com/ray-project/ray/issues/18916). Hence, this PR will add support a generic `timeout` decorator that works per process and continues execution if the underlying function execution takes longer than expected. The ray task will fail with `TimeoutError`.
=> Added timeout for merge and hash bucket tasks as a symptomatic fix

.github/workflows/ci.yml, .github/workflows/publish-to-pypi.yml, deltacat/__init__.py, requirements.txt, setup.py
This PR updates boto3 and s3fs versions to their latest versions. The current versions conflict with various AWS APIs.
It also drops support for Python 3.7, which is
- Almost a year past EOL
- Not compatible with the latest boto3 version
Also updates daft.
Updating S3Fs introduced a regression in some of the benchmarks -- the mechanism for this is unknown at the moment, and it's not clear if this would translate to an actual performance regression in production. We're proceeding with caution.
=> Update boto3 and s3fs dependencies, drop Python 3.7 support

deltacat/compute/compactor_v2/constants.py, deltacat/compute/compactor_v2/steps/hash_bucket.py, deltacat/compute/compactor_v2/steps/merge.py, deltacat/tests/utils/test_resources.py, deltacat/utils/resources.py
Ray is running multiple tasks on a single process which breaks the functionality as per documentation. Removed the @timeout annotation as well because it's not very useful in large-scale Ray application's context and is a dead code now. 
Note: A file level timeout is added by DAFT team in `getdaft==0.2.25` which will resolve this issue symptomatically. We will also start receiving logs which will allow us to root cause stuck daft reads.
=> Remove @timeout annotation

deltacat/compute/compactor_v2/compaction_session.py, deltacat/tests/compute/compact_partition_rebase_test_cases.py, deltacat/tests/compute/compactor_v2/test_compaction_session.py, deltacat/tests/compute/test_compact_partition_rebase.py, deltacat/tests/compute/test_util_create_table_deltas_repo.py, deltacat/tests/local_deltacat_storage/__init__.py, dev-requirements.txt
This change adds a check for the rebase source partition locator. This is to prevent erroneously marking tables as in-place compacted during rebase jobs.
Tested by running a rebase job in personal stack.
=> Modify in-place compacted check to include rebase source partition locator

deltacat/compute/compactor_v2/compaction_session.py, deltacat/compute/compactor_v2/constants.py
The @metrics annotation uses a method name on which it is annotated. In this case, it annotated over a decorator and hence `categorize_errors` will be used to emit metrics. This PR hardcodes prefix so that we don't have to change dashboards when additional annotations are added.
=> Adding metric prefix to get the right method name

deltacat/tests/compute/compactor/utils/test_round_completion_file.py
- Added a test case which tests rcf with destination with None partition ID can be read/written.
=> Ensure destination with None locator can be read/written

deltacat/compute/compactor_v2/utils/primary_key_index.py
Fix a bug where we generate pk hash column twice
=> Avoid running bucketing twice

deltacat/exceptions.py, deltacat/tests/compute/compactor_v2/steps/test_hash_bucket.py, deltacat/tests/compute/compactor_v2/steps/test_merge.py
Earlier we were only looking for deltacat storage in args and top level keys in kwargs. However, there are cases when we have to extract values of kwargs and look for deltacat storage inside them to categorize error correctly.
=> Look for deltacat storage in both args and kwargs

deltacat/__init__.py, deltacat/tests/utils/test_daft.py, deltacat/tests/utils/test_pyarrow.py, dev-requirements.txt, requirements.txt, setup.py
- Added couple of tests.
- Upgraded daft version
- This fixes an issue when column name not in parquet schema is passed.
=> Upgrade daft and adding two more tests for schema evolution usecase

deltacat/aws/clients.py, requirements.txt
- STS throttle when the new instance is spin up causing `CredentialRetrievalError`. 
- As a symptomatic fix, we are now waiting 10 mins instead of 5 mins earlier.
=> Now waiting for 10 mins instead of 5 to fetch credentials from STS

deltacat/compute/compactor/compaction_session.py, deltacat/compute/compactor/model/compact_partition_params.py, deltacat/compute/compactor/model/compaction_session_audit_info.py, deltacat/compute/compactor/model/delta_annotated.py, deltacat/compute/compactor/steps/hash_bucket.py, deltacat/compute/compactor_v2/compaction_session.py, deltacat/compute/compactor_v2/constants.py, deltacat/compute/compactor_v2/private/compaction_utils.py, deltacat/compute/compactor_v2/steps/merge.py, deltacat/compute/compactor_v2/utils/delta.py, deltacat/compute/compactor_v2/utils/io.py, deltacat/compute/compactor_v2/utils/merge.py, deltacat/tests/compute/compact_partition_multiple_rounds_test_cases.py, deltacat/tests/compute/compactor_v2/test_compaction_session.py, deltacat/tests/compute/test_compact_partition_multiple_rounds.py, deltacat/tests/compute/test_util_create_table_deltas_repo.py, deltacat/tests/local_deltacat_storage/__init__.py
Added multi round splitting support:
- New num_round parameter in CompactPartitionParams (default is 1)
- New helper function that groups uniform_deltas into batches if num_rounds is not 1
- New pytests to test aggregation across multiple rounds (drop_duplicates = False) and important asserts (currently not supporting backfill for multiple rounds, hb count should not be 1 for multiple rounds, etc.)
- Bug fix in read_delta_file_envelopes
=> Multi round rebase compaction support

deltacat/__init__.py, deltacat/compute/compactor_v2/compaction_session.py, deltacat/compute/compactor_v2/private/compaction_utils.py, deltacat/tests/compute/compactor_v2/test_compaction_session.py
This PR ensures the RCF stats (inputInflation and averageRecordSizeBytes) are calculated based on the incremental data only.
=> Adding a test to assert RCF values are calculated correctly

deltacat/__init__.py, deltacat/compute/compactor_v2/private/compaction_utils.py
This PR clears object store store after every round. This change was missed in the previous PR and was discovered after running a test run.
=> Clear object store after every round

deltacat/__init__.py, deltacat/compute/compactor_v2/private/compaction_utils.py
This PR reverts the code change (https://github.com/ray-project/deltacat/pull/357/files) performed to clear object store after every round. Clearing entire object store will also prevent any partitions that are running in parallel to complete. Hence, a dedicated task will be taken up to address this use-case.
=> Revert "Clear object store after every round"

deltacat/compute/compactor_v2/utils/content_type_params.py, deltacat/compute/resource_estimation/delta.py, deltacat/tests/compute/resource_estimation/test_delta.py
This PR allows us to set DEFAULT_V2 option for both parquet and utsv files by handling the null for average record sizes.
=> Allow DEFAULT_V2 when avg record size is absent

deltacat/__init__.py, deltacat/io/memcached_object_store.py, deltacat/io/s3_object_store.py
Here is the relevant documentation showing `noreply` is correct (rather than `no_reply`): https://pymemcache.readthedocs.io/en/latest/apidoc/pymemcache.client.base.html#pymemcache.client.base.Client.delete_many
=> Hotfix for memcached noreply flag + bump version

deltacat/__init__.py, deltacat/compute/resource_estimation/delta.py, deltacat/tests/compute/resource_estimation/test_delta.py
This commit ensures the pyarrow table size 0 is handled appropriately. 
The size of the arrow table could be zero even if the file itself isn't 0.
N/A
Existing UTs pass. No impact,. 
Added test cases to repro 0 arrow table size. 
None
- [x ] If this is a bugfix, regression tests have been added
=> Fix divide by zero error when pyarrow table size comes out 0

deltacat/compute/compactor_v2/private/compaction_utils.py, deltacat/tests/compute/test_compact_partition_incremental.py, deltacat/tests/compute/test_compact_partition_multiple_rounds.py, deltacat/tests/compute/test_compact_partition_rebase.py, deltacat/tests/compute/test_compact_partition_rebase_then_incremental.py
This changes fixes a bug that resulted in RCF to be written incorrectly when there were multiple rounds. 
N/A
Bug Fix
The impact is high as this will lead to data loss in subsequent incremental jobs.
The assertion that ensures all files are covered as part of RCF is added. 
None
=> Fix a bug that caused the RCF to be written incorrectly during multiple rounds

.pre-commit-config.yaml, deltacat/__init__.py
version bump
https://github.com/ray-project/deltacat/pull/439
See testing section: https://github.com/ray-project/deltacat/pull/439
=> Bump version to 1.1.28

.gitignore, deltacat/aws/s3u.py, deltacat/examples/rivulet/data.csv, deltacat/examples/rivulet/pytorch_demo.ipynb, deltacat/storage/rivulet/dataset.py, deltacat/utils/export.py, requirements.txt, setup.py
- **`dataset.from_json`**
- **Purpose:** Create a Rivulet dataset from a JSON file.
- **Functionality:** Similar to `from_parquet`.
- **Limitations:** Supports only single JSON files at present, as PyArrow does not natively handle directories for JSON datasets.
- **`dataset.from_csv`**
- **Purpose:** Create a Rivulet dataset from a CSV file.
- **Functionality:** Similar to `from_parquet`.
- **Limitations:** Supports only single CSV files at present, as PyArrow does not natively handle directories for CSV datasets.
**Future Enhancement:** Extend both `from_json` and `from_csv` to support directory imports.
- **`dataset.export`**
- **Purpose:** Export Rivulet datasets into multiple formats.
- **Supported Formats:** Parquet, JSON, and Feather.
- **Functionality:** Provides a unified method …
=> Add support for JSON and CSV data formats

deltacat/compute/compactor_v2/utils/primary_key_index.py, deltacat/tests/compute/compactor_v2/utils/test_primary_key_index.py
This change ensures the resultant record batches size does not exceed 2GB. Pyarrow uses int offsets and hence cannot hold arrays more than 2GB as the offset would overflow. 
The fix had already been applied but missed a corner case. 
Address the corner case. 
No impact on existing job runs. However, this change will allow onboarding tables with large parquet files.
Added functional tests for both cases. 
Very Low
=> Truncate the table if the size exceeds more than 2GB

deltacat/compute/compactor_v2/utils/dedupe.py, deltacat/tests/compute/compact_partition_test_cases.py
Fix "pyarrow.lib.ArrowInvalid: cannot construct ChunkedArray from empty vector and omitted type"
Creating an empty chunked array requires type to be passed.
Pass type arg
Handles cases with empty incremental hash bucket
- Functional tests are added.
- Integ tests performed manually with failing table.
Very low. The existing functional tests passed and changes are backward compatible.  
=> Fix pyarrow.lib.ArrowInvalid: cannot construct ChunkedArray

deltacat/storage/rivulet/metastore/sst_interval_tree.py, deltacat/tests/storage/rivulet/test_sst_interval_tree.py
Fixes an issue when scanning a rivulet dataset with a query expression where the min key matches the global min key would always return no records.
During testing, @anshumankomawar found that scans involving a query expression where the min key matches the global min key would incorrectly return no records (unless the min key happened to be 0).
* Fixed guard conditions that incorrectly handled numeric key values of `0` as "Falsy" values.
* Pinned min key index to 0 when bisecting the interval tree (whereas before it would potentially use an index of `-1`).
This should allow rivulet to return expected records even when min key matches the global min key.
Added a new functional unit test that fails without the corresponding bugfix
`make test` to ensure no regressions.
Low. Existing …
=> fix block group generation when min key matches global min key

deltacat/compute/compactor_v2/constants.py, deltacat/compute/compactor_v2/steps/merge.py, deltacat/compute/compactor_v2/utils/primary_key_index.py, deltacat/tests/compute/compactor_v2/test_compaction_session.py, deltacat/tests/test_utils/pyarrow.py, deltacat/utils/pyarrow.py
This change addresses cases where the previous hash bucket size is over 2GB.
is_in op in arrow doesn't allow the first arg to be over 2GB in size. 
To overcome the arrow limitation, we cast the first arg to large_string. 
No impact to existing tables. Only the tables that were failing before will now run through this codepath. 
A functional test is added. 
Note: reduced the memory used by functional test to be able to run it on standard github hosted runners.
Very low. 
=> Resolve ArrowCapacityError when processing >2GB

deltacat/storage/rivulet/feather/file_reader.py, deltacat/storage/rivulet/parquet/file_reader.py, deltacat/storage/rivulet/reader/block_scanner.py, deltacat/storage/rivulet/reader/data_reader.py, deltacat/storage/rivulet/reader/reader_type_registrar.py, deltacat/tests/storage/rivulet/reader/test_data_scan.py, deltacat/tests/storage/rivulet/test_utils.py
Found an issue with schema fields not being respected during dataset scan. If new schemas are created and explicitly mentioned in a DataScan the returned fields should be limited to that of the schema.
Updated the `FileReader implementations to select columns during batch read. This functionality is already provided by pyarrow through methods like batch.select which have an optional column field.
- `make test` to run existing tests. 
- verified changes with manual testing of DataScan ensured outputs are as expected
- added a end to end test for scan with multiple schemas to highlight the fix
=> fix: respect schema fields in file reader

deltacat/storage/rivulet/writer/memtable_dataset_writer.py, deltacat/tests/storage/rivulet/writer/test_memtable_dataset_writer.py
Manifests currently include data from each write and do not remove data from previous writes. The issue is in the dataset writer flush method. Clearing sst_files and data_files after each flush ensures the manifest contains data from only that flush.
- `make test` for existing tests. 
- added a test for `MemtableDatasetWriter` to highlight this bug.
=> fix: clear data and sst files after manifest flush

deltacat/tests/utils/test_pyarrow.py, deltacat/utils/pyarrow.py
This change adds a new kwarg that can be used to override the content encoding in the metadata. This applies to every parquet file. The reason we are adding this is to gradually dial up all parquet files to read via identity encoding. 
The internal catalog metadata incorrectly sets content type of parquet files as gzip even though full file isn't gzip compressed.
Add a new kwarg which can be used to override the content encoding for parquet
Unblocks compaction of new tables.
Functional tests
Very low as it doesn't affect the current codepath unless the kwarg is set. 
=> Allow overriding content encoding

deltacat/__init__.py
- Patch version bump to 1.1.30
- https://github.com/ray-project/deltacat/pull/470
See testing section: https://github.com/ray-project/deltacat/pull/470
=> Patch version bump to 1.1.30

Makefile, deltacat/tests/compute/converter/conftest.py, deltacat/tests/compute/converter/test_convert_session.py, dev-requirements.txt, requirements.txt, setup.py
This PR adds Initial test setup for converter using Spark and Pyiceberg. It reuse the MakeFile and docker setup in DeltaCAT. 
make test-converter
Will follow up with test cases that use Pyiceberg to generate equality deletes and Spark to read the position deletes we produced to mimic the end-to-end converter workflow and validate the results. 
For read, since Spark can't produce equality deletes currently, we should explore to generate equality deletes using Pyiceberg directly. 
For write, this test setup could also validate the position delete converter write in sense of position delete file link, naming, table properties convertion, etc.
=> Initial Test Setup for Converter using Spark and Pyiceberg

Makefile, deltacat/__init__.py, deltacat/storage/__init__.py, deltacat/storage/interface.py, deltacat/storage/main/impl.py, deltacat/storage/model/list_result.py, deltacat/storage/model/locator.py, deltacat/storage/model/metafile.py, deltacat/storage/model/partition.py, deltacat/storage/model/stream.py, deltacat/storage/model/table.py, deltacat/storage/model/table_version.py, deltacat/storage/model/transaction.py, deltacat/tests/storage/main/test_main_storage.py, deltacat/tests/storage/model/test_metafile_io.py, deltacat/tests/storage/model/test_table_version.py, setup.py
Initial implementation of DeltaCAT storage w/o implementations of methods operating on deltas. TODOs show most pending work. One of the larger changes between this and the final implementation will involve ensuring that each storage interface method completes within the context of a single transaction.
This PR merges common changes from https://github.com/ray-project/deltacat/pull/484 into a single implementation.
Partial unit test coverage is provided over basic storage methods from Namespace to Stream. Additional unit tests will be added in a follow-up PR.
=> Partial DeltaCAT Native Storage Implementation

deltacat/compute/compactor_v2/utils/task_options.py, deltacat/tests/compute/compactor_v2/utils/test_task_options.py
This change fixes a possible ZeroDivisionError error case in `_get_merge_task_options`
-It's plausible and permissible for the round completion info parameter object to contain zero values for `compacted_pyarrow_write_result.records` and `compacted_pyarrow_write_result.file_bytes` round completion info argument may contain
- Falling back to the `PYARROW_INFLATION_MULTIPLIER` and `DEFAULT_AVERAGE_RECORD_SIZE_BYTES` for calculating previous_inflation and average_record_size respectively when `compacted_pyarrow_write_result.records` or `compacted_pyarrow_write_result.file_bytes` are zero
- Adding unit testing coverage for `_get_merge_task_options` from no coverage including the default case
- Adding additional type hints
- Small blast radius - this should enable the compaction of incremental …
=> Bugfix: ZeroDivisionError possible when calculating previous_inflation and average_record_size

deltacat/__init__.py
- Patch version bump to 1.1.31
- https://github.com/ray-project/deltacat/pull/490
See testing section: https://github.com/ray-project/deltacat/pull/470
=> Patch version bump to 1.1.31

deltacat/storage/iceberg/impl.py
Resolving the following TODOs in create_table_vesrion: 
```# TODO: ensure catalog.create_table() is idempotent ```
```# TODO: get table and commit new metadata if table already exists?```
Simple changes to get onboarded onto the project. 
Addressed catalog.create_table() idempotecy --> attempts to load existing iceberg table; if it doesn't exist it performs catalog.create_table()
Addressed new metadata commit to existing table --> if table exists, uses the iceberg table transaction and sets the properties to the table_properties. 
n/a
Passes all current tests. Need guidance on how/where to add tests.
n/a
=> TODOs in storage/iceberg/impl.py in create_table_version

deltacat/tests/utils/test_pyarrow.py, deltacat/utils/pyarrow.py
This change no longer raises ContentTypeValidationError from  `s3_file_to_parquet` if appropriately overridden
-Although the ["Allow overriding content encoding" bugfix](https://github.com/ray-project/deltacat/pull/462/files)
was merged into DeltaCAT and released in [1.1.30](https://github.com/ray-project/deltacat/releases/tag/1.1.30), the overriding does not properly happen during the compaction session which results in in a raised [ContentTypeValidationError](https://github.com/ray-project/deltacat/blob/79475284f2539f8b1b82fe80878ab593da930d0b/deltacat/utils/pyarrow.py#L483)
when the underlying file is gzip encoded - even if the `override_content_encoding_for_parquet` is provided. 
- Added check for override_content_encoding_for_parquet
- Adding unit testing coverage for …
=> Bugfix: `s3_file_to_parquet` function doesn't override content encoding if provided with the override kwarg

.github/workflows/ci.yml, deltacat/__init__.py
- Patch version bump to 1.1.32
- https://github.com/ray-project/deltacat/pull/506
See testing section: https://github.com/ray-project/deltacat/pull/506
=> Patch version bump to 1.1.32

README-development.md, deltacat/catalog/v2/catalog_impl.py, deltacat/exceptions.py, deltacat/storage/interface.py, deltacat/storage/main/impl.py, deltacat/storage/model/namespace.py, deltacat/storage/model/table.py, deltacat/tests/catalog/main/test_catalog_impl_namespace_operations.py, deltacat/tests/catalog/main/test_catalog_impl_table_operations.py
This PR continues work on the catalog interface layer for Deltacat. It primarily focuses on implementing table related functions.
Functions Implemented:
- alter_table
- create_table
- drop_table
- list_tables
- get_table
- rename_table
Also includes minor bugfixes and better exception handling in the storage interface layer.
- ran existing tests using `make test`
- added new tests for catalog table functions
There are some follow up tasks that have been added as TODO's.
=> feat: implement catalog table functions

Makefile, deltacat/compute/converter/converter_session.py, deltacat/compute/converter/model/convert_input.py, deltacat/compute/converter/model/converter_session_params.py, deltacat/compute/converter/pyiceberg/replace_snapshot.py, deltacat/compute/converter/steps/convert.py, deltacat/compute/converter/utils/converter_session_utils.py, deltacat/compute/converter/utils/iceberg_columns.py, deltacat/compute/converter/utils/s3u.py, deltacat/tests/compute/converter/conftest.py, deltacat/tests/compute/converter/test_convert_session.py, deltacat/tests/compute/converter/utils.py, dev/_sandbox/compute/converter/example_single_merge_key_converter.py
This PR adds working end-to-end converter find deletes compute happy case test. 
With 1. Minio S3 endpoint replaced in S3 file system 2. Daft download parquet file mocked, 
We are able to test the compute part end-to-end. 
Future dev work adding new features can use the same setup to test correctness.
If this is a bugfix, explain how the fix has been tested to ensure the bug is resolved without introducing new issues.
If this is a bugfix, assess the risk of regression caused by this fix …
=> [Converter][Test]Add working end-to-end converter compute test with Minio S3 endpoint

deltacat/__init__.py, deltacat/api.py, deltacat/catalog/__init__.py, deltacat/catalog/delegate.py, deltacat/catalog/interface.py, deltacat/catalog/main/impl.py, deltacat/catalog/model/catalog.py, deltacat/catalog/model/properties.py, deltacat/catalog/v2/catalog_impl.py, deltacat/constants.py, deltacat/env.py, deltacat/examples/basic_logging.py, deltacat/examples/common/fixtures.py, deltacat/examples/iceberg/iceberg_bucket_writer.py, deltacat/examples/iceberg/iceberg_reader.py, deltacat/exceptions.py, deltacat/tests/catalog/main/test_catalog_impl_namespace_operations.py, deltacat/tests/catalog/main/test_catalog_impl_table_operations.py, deltacat/tests/storage/main/test_main_storage.py, deltacat/tests/storage/model/test_metafile_io.py, deltacat/tests/test_deltacat.py, deltacat/tests/test_deltacat_api.py, requirements.txt, setup.py
Initial WIP draft of DeltaCAT FS API w/ limited functionality for creating/getting/copying catalogs and namespaces (see `test_deltacat_api.py` for an example). Also adds bug fixes and refactoring of catalog properties to support multi-process-safe named catalog registration in local or distributed Ray apps/clusters.
=> Initial Working Prototype of DeltaCAT FS API w/ Limited Catalog & Namespace Get/Put/Copy Functionality

deltacat/compute/converter/converter_session.py, deltacat/compute/converter/model/convert_input.py, deltacat/compute/converter/model/convert_input_files.py, deltacat/compute/converter/model/converter_session_params.py, deltacat/compute/converter/pyiceberg/replace_snapshot.py, deltacat/compute/converter/steps/convert.py, deltacat/compute/converter/steps/dedupe.py, deltacat/compute/converter/utils/converter_session_utils.py, deltacat/compute/converter/utils/iceberg_columns.py, deltacat/compute/converter/utils/io.py, deltacat/tests/compute/converter/test_convert_session.py, requirements.txt
Records with same primary key/identify fields will be deduped with this PR, the purpose is that we can enforce primary key uniqueness as well as finding primary keys to be deleted based on equality delete files within same operation(No need to download into memory same files again). All records meant to be either deduped or deleted will be output in form of position deletes.
If this is a bugfix, explain how the fix has been tested to ensure the bug is resolved without introducing new …
=> Add enforce_primary_key_uniqueness support to converter

deltacat/compute/compactor_v2/steps/merge.py
- [Final parameter](https://github.com/ray-project/deltacat/blob/9a0a624f91e6de6708626a3d457649348dcd8b82/deltacat/compute/compactor_v2/steps/merge.py#L630) of [`MergeResult`](https://github.com/ray-project/deltacat/blob/f2d11b21c8f5c2421d70fcf9b3fa4769d7f6c9e8/deltacat/compute/compactor_v2/model/merge_result.py#L7) is using [`peak_memory_usage_bytes`](https://github.com/ray-project/deltacat/blob/f2d11b21c8f5c2421d70fcf9b3fa4769d7f6c9e8/deltacat/compute/compactor_v2/model/merge_result.py#L12), which is already returned as the [fourth parameter](https://github.com/ray-project/deltacat/blob/f2d11b21c8f5c2421d70fcf9b3fa4769d7f6c9e8/deltacat/compute/compactor_v2/steps/merge.py#L566) instead of `time.time()` as an argument
- Root-cause of a bug in  the `task_completed_at` calculation
- Final …
=> Bugfix: Final parameter of `MergeResult` is using peak_memory_usage_bytes instead of time.time() (task_completed_at)

deltacat/__init__.py
- Patch version bump to 1.1.33
- https://github.com/ray-project/deltacat/pull/506
The change is backward compatible and fixes an audit logging bug.
See testing section: https://github.com/ray-project/deltacat/pull/506
=> Patch version bump to 1.1.33

deltacat/compute/compactor_v2/utils/content_type_params.py, deltacat/compute/compactor_v2/utils/io.py, deltacat/compute/resource_estimation/delta.py, deltacat/tests/compute/compactor_v2/utils/test_content_type_params.py
Uniform delta creation (compaction path) not propagating the `file_reader_kwargs_provider` when appending content type params to the deltas
- Fixes the `override_content_encoding_for_parquet` bug for compaction flow described in [505](https://github.com/ray-project/deltacat/pull/505/files) and [462](https://github.com/ray-project/deltacat/pull/462/files). Content encoding is appropriately overridden for *resource estimation* but not building uniform deltas during *compaction* 
- `append_content_type_params` signature updated to accept the `file_reader_kwargs_provider` explicitly as an optional parameter
- Additional logging
- Optional parameter added to the signature of public method `append_content_type_params`. Could impact callers that invoke `append_content_type_params` using …
=> Bugfix: Uniform delta creation (compaction path) not propagating the file_reader_kwargs_provider when appending content type params to the deltas

deltacat/__init__.py
- Patch version bump to 1.1.34
- https://github.com/ray-project/deltacat/pull/522
The change is backward compatible and fixes an audit logging bug.
See testing section: https://github.com/ray-project/deltacat/pull/506
=> Patch version bump to 1.1.34

deltacat/__init__.py, deltacat/compute/compactor_v2/constants.py, deltacat/compute/compactor_v2/steps/merge.py, deltacat/tests/compute/compactor_v2/test_compaction_session.py, deltacat/tests/compute/test_compact_partition_incremental.py, deltacat/tests/compute/test_compact_partition_multiple_rounds.py, deltacat/tests/compute/test_compact_partition_rebase.py, deltacat/tests/compute/test_compact_partition_rebase_then_incremental.py
This change adds a bucketing spec validation to assert and identify tables whose records have drifted from their original hash bucket. 
We observed a small number of records which drifted from their original hash bucket in one of the production tables.  Hence, adding the validation check will detect any future drift quickly and help confirm blast radius. 
This PR brings two features which can be enabled by setting below environment variables:
1. ENABLE_BUCKETING_SPEC_COMPLIANCE_LOGGING: Ensures that data is compliant with bucketing spec, just logs a message without failing the job. 
2. ENABLE_BUCKETING_SPEC_COMPLIANCE_ASSERTION: Ensures that data is compliant with bucketing spec, throws an error otherwise.
The functionality, when enabled has negative impact on cost. Hence, should be …
=> Add bucketing spec validation for existing compacted table

deltacat/api.py, deltacat/catalog/model/catalog.py, deltacat/tests/catalog/iceberg/test_iceberg_catalog.py, deltacat/tests/catalog/test_catalogs.py, deltacat/tests/compute/compactor/utils/test_io.py, deltacat/tests/compute/compactor_v2/deletes/test_delete_utils.py, deltacat/tests/compute/compactor_v2/test_compaction_session.py, deltacat/tests/compute/conftest.py, deltacat/tests/compute/resource_estimation/test_delta.py, deltacat/tests/compute/test_compact_partition_incremental.py, deltacat/tests/compute/test_compact_partition_multiple_rounds.py, deltacat/tests/compute/test_compact_partition_rebase.py, deltacat/tests/compute/test_compact_partition_rebase_then_incremental.py
Follow on from PR https://github.com/ray-project/deltacat/pull/517
Remove Namespace support in Catalogs. Also refactor compute tests to use a sqlite DB in a temporary directory, since the tests were not properly cleaning up the sqlite file that previously used the test directory
=> Remove ray namespace support in Catalogs & minor test refactors

deltacat/__init__.py, deltacat/compute/compactor_v2/compaction_session.py, deltacat/compute/compactor_v2/model/merge_input.py, deltacat/compute/compactor_v2/private/compaction_utils.py, deltacat/compute/compactor_v2/steps/merge.py, deltacat/compute/compactor_v2/utils/merge.py
This change checks for hash bucket value computed by the nodes running hash bucketing tasks and produces INFO log if it's non-compliant with bucketing spec. 
Checking for consensus can help us catch this issue at scale during runtime as all our efforts to reproduce this bug in test environment have failed. 
Adds validation of bucketing spec on incremental table as well for added cost. 
No impact to existing runs. A log message will be produced on every non-compliance. 
Functional tests exists for checking happy case and failure cases. 
None
=> Adding incremental validation to assert consensus of hash bucket value

.github/workflows/publish-to-pypi.yml
Add missing flag to pytest command that was causing workflow to fail.
=> fix: add missing -m flag to pytest command

deltacat/__init__.py
Removed `IcebergCatalog` import from required imports. Line 65 adds this import if the `pyiceberg` dependency is installed. This prevents new installations from failing if `pyiceberg` is not installed.
=> fix: remove IcebergCatalog import from required imports

deltacat/compute/compactor_v2/utils/primary_key_index.py
This change fixes a DQ issue that was caused due to inconsistent grouping of bucketed records. The pyarrow `groupby` method *almost* always returns the keys (on which the records were grouped) in the same order as they appear in the input. Algorithm relied on this invariant for correctness. However, we missed adding an assertion for the same. In rare scenarios, the order of the keys changed which led to incorrect assignment of hash buckets to respective record groups and caused DQ issue in the tables.
The ordering of keys in the output will be consistent with the input if pyarrow uses `exactly one thread` to execute the `groupby` operation. However, in some `unknown` scenarios, pyarrow could be using multi-threading to speed up the grouping operation which has resulted in inconsistent …
=> Fix DQ issue due to inconsistent grouping of bucketed records

deltacat/__init__.py, deltacat/compute/resource_estimation/delta.py, deltacat/compute/resource_estimation/model.py, deltacat/tests/compute/resource_estimation/test_delta.py
This change adds a new resource estimation method which falls back to inflation after exhausting maximum files to sample. This allows us to use the same function in succession and use the inflation calculated from sampled files. 
Helps with better estimate memory during compaction. 
Adds a new resource estimation method. 
This change adds a new functionality. So, no impact on estimation methods.
Functional tests have been added. 
No risk. 
=> Add a new resource estimation method to fallback to inflation

deltacat/storage/model/manifest.py, deltacat/tests/storage/model/test_manifest.py
Implementing `Manifest.from_json()` method to support deserialization from Manifest json string.
This is needed to support parsing Manifest that is returned from Glue partition.
- Added unit test and passed
=> chore: add Manifest.from_json() method

requirements.txt, setup.py
bump up daft version to 0.4.13 which is compatible with AL2.
- e2e Iceberg read example works
=> chore: upgrade daft version

deltacat/compute/converter/constants.py, deltacat/compute/converter/converter_session.py, deltacat/compute/converter/model/convert_input.py, deltacat/compute/converter/model/converter_session_params.py, deltacat/compute/converter/pyiceberg/overrides.py, deltacat/compute/converter/steps/convert.py, deltacat/compute/converter/steps/dedupe.py, deltacat/compute/converter/utils/convert_task_options.py, deltacat/compute/converter/utils/io.py, deltacat/compute/converter/utils/s3u.py, deltacat/tests/compute/converter/test_convert_session.py
This PR adds two additional features for customized converter job options, mainly:
1. File location override: Allow position delete produced to be written to customized location. 
Note this change does not directly override the Iceberg location provider implementation because currently DeltaCAT converter did not go through Iceberg write path. Instead, it rely on `UuidBlockWritePathProvider` for customized write path options.
2. `data_file_statistics_from_parquet_metadata()` method override: As an workaround for injecting reserved column stats instead of breaking the current logic of getting all columns from schema.
Discuss any potential impacts the changes may have …
=> [Converter] Add location provider override to allow customized file location; Override reserved columns stats populating logic

deltacat/compute/converter/constants.py, deltacat/compute/converter/converter_session.py, deltacat/compute/converter/model/convert_input.py, deltacat/compute/converter/model/converter_session_params.py, deltacat/compute/converter/pyiceberg/overrides.py, deltacat/compute/converter/steps/convert.py, deltacat/compute/converter/steps/dedupe.py, deltacat/compute/converter/utils/convert_task_options.py, deltacat/compute/converter/utils/iceberg_columns.py, deltacat/compute/converter/utils/io.py, deltacat/compute/converter/utils/s3u.py, deltacat/constants.py, deltacat/tests/compute/converter/test_convert_session.py, deltacat/tests/experimental/daft/test_deltacat_daft_integration.py, deltacat/tests/storage/rivulet/test_dataset.py
This PR mainly includes two additions:
1. Adds support for concatenating multiple identifier hash column values to evaluate value equality when enforcing identifier column uniqueness.
2. Refactor parquet file to Iceberg data file conversion to be Ray distributed tasks. Observed that when testing with scale, Pyiceberg function `parquet_file_to_iceberg_data_file` calls `parquet.download_metadata` and `filesystem._get_file_info()` under the hood, which are performance bottlenecks. So refactor the conversion functions to be Ray distributed tasks.
1. Adding concatenating hash column value logic.
2. Unit tests for multiple identifier value test case.
Discuss any potential impacts the changes may have on existing …
=> [Converter] Multiple pk support; Refactor parquet file to Iceberg data file conversion functions to be Ray distributed tasks.

deltacat/compute/converter/converter_session.py, deltacat/compute/converter/model/convert_input.py, deltacat/compute/converter/model/convert_result.py, deltacat/compute/converter/model/converter_session_params.py, deltacat/compute/converter/pyiceberg/overrides.py, deltacat/compute/converter/steps/convert.py, deltacat/compute/converter/steps/dedupe.py, deltacat/compute/converter/utils/convert_task_options.py, deltacat/compute/converter/utils/io.py, deltacat/tests/compute/converter/test_convert_session.py
This PR mainly adds:
1. Assertion around lower-level Pyarrow function like concatenate arrays; Daft string casting to allow us to detect potential issues earlier on.
2. Aggregate stats mainly for input/output record counting, in-memory/on-disk sizes.
Note file changes contain previous stacked PR #542, will rebase once #542 is merged. (Rebased)
If this is a bugfix, explain how the fix has been tested to ensure the bug is resolved without introducing new issues.
If this is a bugfix, assess …
=> [Converter] Add assertion for correctness; Add aggregate stats and additional logging

deltacat/catalog/model/catalog.py, deltacat/utils/daft.py
As part of Daft release `0.4.15` the existing `TermVisitor` was replaced in favor of a `ExpressionVisitor` and `PredicateVisitor`. Find more here https://github.com/Eventual-Inc/Daft/blob/main/daft/expressions/visitor.py#L14.
This PR updates DaftToDeltacat Visitor to implement the new `PredicateVisitor` interface.
=> feat: update daft<->deltacat visitor to use new daft predicate visitor

deltacat/tests/compute/converter/test_convert_session.py
Use parameterized test cases to reduce duplicated test setup code and standardize converter input/mock/assertions construction functions. This cleanup can help other devs to understand the converter test setups and easily add new test cases in future development.
All existing tests passing.
=> [Converter] Use parameterized test cases to restructure and clean up converter tests

deltacat/storage/model/schema.py
Updated merge key validation to allow PyArrow large_strings
Reading Iceberg table yielded error due to merge key field type, no real reason to exclude large_strings. 
Updated _validate_merge_key to allow PyArrow large_strings as well. 
Unit testing, build passed.
N/A
Related issues/context:
https://github.com/apache/iceberg-python/issues/1128
https://github.com/apache/iceberg-python/pull/929#issuecomment-2239084293
=> Updated merge key validation to allow PyArrow large_strings

deltacat/experimental/storage/iceberg/iceberg_scan_planner.py, deltacat/experimental/storage/iceberg/visitor.py, deltacat/tests/experimental/storage/iceberg/test_visitor.py
Added partition-level predicate pushdown for Iceberg.
To-do
Added a DeltaCAT to PyIceberg expression visitor to utilize PyIceberg APIs for partition-level predicate pushdown, along with corresponding test suites. Updated IcebergScanPlanner to use said APIs if applicable.
Unit tests, integration tests, etc all pass.
=> Added partition-level predicate pushdown for Iceberg

deltacat/catalog/model/catalog.py, deltacat/catalog/model/properties.py, deltacat/constants.py, deltacat/tests/catalog/test_catalogs.py, deltacat/tests/conftest.py, deltacat/utils/config_loader.py
Added using config.yaml file as a second choice option to initialize DeltaCAT catalog instead of relying on .init() call passing in parameters explicitly. 
To reduce tasks for users and expose less internal mechanisms.
- Created config.yaml parser for initialize()
- Wrote according test
Only adds possible functionality, backwards-compatible. 
make test
Next steps will be to create enums and expand existing catalog types. ex. Iceberg
=> Rudimentary catalog init refactoring to use a config file
