ray-project/deltacat

deltacat/compute/stats/basic.py, deltacat/compute/stats/models/delta_column_stats.py, deltacat/compute/stats/models/delta_stats.py, deltacat/compute/stats/models/delta_stats_cache_result.py, deltacat/compute/stats/models/manifest_entry_stats.py, deltacat/compute/stats/models/stats_result.py, deltacat/compute/stats/utils/intervals.py, deltacat/compute/stats/utils/io.py, deltacat/compute/stats/utils/manifest_stats_file.py
Adding/updating docstrings for stats collection public APIs.
Linked Issues:
- #8
=> Stats collection docstrings

deltacat/compute/stats/basic.py, deltacat/compute/stats/utils/intervals.py, deltacat/compute/stats/utils/io.py, deltacat/tests/stats/test_intervals.py
Addresses #3 to allow clients to conveniently fetch stats for unbounded intervals
=> [Stats] Add support for infinite range with delta stream positions

deltacat/aws/s3u.py, requirements.txt, setup.py
This PR contains changes needed for ray 1.10.0 release.
=> [ray-1.10.0] Stage changes for ray 1.10.0 release

deltacat/compute/metastats/meta_stats.py, deltacat/compute/metastats/stats.py, deltacat/compute/metastats/utils/ray_utils.py
This PR adds changes to parallel stats collection.
=> [metastats] parallel stats collection

deltacat/compute/compactor/compaction_session.py, deltacat/utils/placement.py, deltacat/utils/ray_utils/concurrency.py
Fix below issues:
1. rename `instance_type`.
2. call class method using self. 
3. rename to `PlacementGroupConfig`.
=> Fix placement group to resolve variables

deltacat/compute/compactor/compaction_session.py
Issues: https://github.com/ray-project/deltacat/issues/97
=> Fix compactor code path with only source partition to compact from and no previous rounds

deltacat/compute/compactor/compaction_session.py
add kwargs in `compact_partition`, allow users to pass in any additional catalog-specific metadata
=> add property info

deltacat/__init__.py, deltacat/compute/compactor/compaction_session.py, deltacat/compute/compactor/utils/io.py
[Motivation] https://github.com/ray-project/deltacat/issues/109
=> Add an arg for list_deltas kwargs to disable compacted table resolution

deltacat/compute/compactor/compaction_session.py
=> raise error when the compaction requires multiple rounds

deltacat/compute/compactor/utils/io.py
=> Ensure the list_deltas call returns in ascending order

deltacat/compute/compactor/compaction_session.py, deltacat/compute/compactor/steps/hash_bucket.py, deltacat/compute/compactor/steps/materialize.py, deltacat/compute/compactor/utils/io.py, deltacat/utils/pyarrow.py
=> support read_kwargs_provider arg to compact_partition

deltacat/__init__.py, deltacat/compute/compactor/compaction_session.py
1. The stream position delta will be the last stream position of the data it compacts to ensure it is appropriately sorted in future rounds.
2. Write the round completion file after partition commit to avoid data loss.
=> Fix the stream position of the delta

deltacat/__init__.py, deltacat/compute/compactor/compaction_session.py, deltacat/compute/compactor/steps/dedupe.py, deltacat/compute/compactor/steps/hash_bucket.py, deltacat/compute/compactor/steps/materialize.py, deltacat/compute/compactor/utils/primary_key_index.py, deltacat/io/file_object_store.py, deltacat/io/memcached_object_store.py, deltacat/io/object_store.py, deltacat/io/ray_plasma_object_store.py, deltacat/io/redis_object_store.py, deltacat/io/s3_object_store.py, deltacat/tests/compactor/utils/test_io.py, deltacat/tests/io/test_file_object_store.py, deltacat/tests/io/test_memcached_object_store.py, deltacat/tests/io/test_ray_plasma_object_store.py, deltacat/tests/io/test_redis_object_store.py, deltacat/tests/io/test_s3_object_store.py, deltacat/tests/utils/test_resources.py, requirements.txt, setup.py
#148 
- Tested all implementations on internal 15TB table
- Unit test pending for each object store impl. 
update: unit tests added
=> Refactoring the compact_partition to support different object store implementations

deltacat/__init__.py, deltacat/aws/clients.py
The new change will honor the profile name.
=> Honor profile name in s3 client kwargs

deltacat/__init__.py
Version bumping for https://github.com/ray-project/deltacat/pull/161 changes
=> Version bump to 0.1.18b12

deltacat/compute/compactor/repartition_session.py, deltacat/compute/compactor/steps/repartition.py, deltacat/constants.py
=> Fix stream position and support latest pyarrow

deltacat/compute/compactor_v2/model/merge_input.py, deltacat/compute/compactor_v2/model/merge_result.py, deltacat/compute/compactor_v2/steps/merge.py, deltacat/tests/test_repartition.py
=> Interface for merge v2

deltacat/compute/compactor_v2/steps/merge.py, deltacat/compute/compactor_v2/utils/task_options.py
#150 
This commit aims to fix the issue where pa_write_result was not persisted for materialize result.
=> Write pa write result even when referencing

deltacat/__init__.py, deltacat/io/memcached_object_store.py
#150 
This commit will introduce the noreply flag on the put operation as put operation is eventually consistent.
=> Supporting noreply flag for the memcached object store

deltacat/compute/compactor_v2/utils/task_options.py, deltacat/tests/compute/compactor_v2/utils/test_task_options.py
#150 
This commit will add the `max_retries` and `retry_exceptions` to handle throttling errors.
=> Add retries and retry_exceptions to overcome throttling

deltacat/io/memcached_object_store.py, deltacat/tests/io/test_memcached_object_store.py, deltacat/tests/utils/test_cloudpickle.py, deltacat/utils/cloudpickle.py
=> Split object into smaller chunks before persisting to object store

deltacat/compute/compactor_v2/compaction_session.py
=> Update the input file count, input size and input records

deltacat/compute/compactor_v2/utils/task_options.py
This change adds debug logs for params used when calculating the allocated memory for merge tasks. These logs will help debugging efforts for nodes whose process memory consistently surpasses the allocated memory, thus implying the allocated memory calculation was incorrect.
=> Add debug logs to capture params used for memory calculation

deltacat/__init__.py
This version contains a potentially backward incompatible changes for sungate python.
=> bump deltacat major version 0.3.0

deltacat/compute/compactor_v2/steps/merge.py
Earlier, we would copy by reference even if the RCF compactor delta locator stream ID does not match the provided destination stream id. This would result in an error from the catalog as the manifest entries use unique prefixes for each stream and permissions are isolated. This pull request will enable copy by reference only if stream ID matches.
=> Trigger copy by reference only if previous compacted table exists

deltacat/__init__.py
=> Bump deltacat version to 1.1.1

deltacat/aws/clients.py
Using the boto resource or client on many concurrent Ray tasks (1000+) intermittently throws a `CredentialRetrievalError: Error when retrieving credentials from Ec2InstanceMetadata: No credentials found in credential_source referenced in profile X`. This error is thrown even when the IMDS server is up and health checks have succeeded. This is likely due to query throttling as defined in the [docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html#instancedata-throttling). This change adds retries with exponential backoff to remedy the issue.
=> Add retries on CredentialRetrievalError

deltacat/aws/constants.py, deltacat/aws/s3u.py, deltacat/tests/aws/test_s3u.py
This PR adds retries to `s3u.download` and `s3u.upload`.
=> Add retry to s3u download/upload

deltacat/compute/compactor_v2/utils/task_options.py, deltacat/tests/utils/ray_utils/test_concurrency.py
This commit adds UTs for one of the critical components being used.
=> Add unit tests for critical components being used

deltacat/__init__.py
=> Update version to 1.1.8

deltacat/aws/constants.py, deltacat/aws/s3u.py, deltacat/compute/compactor/model/compact_partition_params.py, deltacat/compute/compactor/model/materialize_result.py, deltacat/compute/compactor_v2/compaction_session.py, deltacat/compute/compactor_v2/constants.py, deltacat/compute/compactor_v2/model/merge_input.py, deltacat/compute/compactor_v2/steps/hash_bucket.py, deltacat/compute/compactor_v2/steps/merge.py, deltacat/compute/compactor_v2/utils/merge.py, deltacat/compute/compactor_v2/utils/primary_key_index.py, deltacat/compute/compactor_v2/utils/task_options.py, deltacat/exceptions.py, deltacat/io/memcached_object_store.py, deltacat/storage/interface.py, deltacat/tests/compute/compact_partition_rebase_then_incremental_test_cases.py, deltacat/tests/compute/compact_partition_test_cases.py, deltacat/tests/compute/compactor_v2/steps/test_merge.py, deltacat/tests/local_deltacat_storage/__init__.py, deltacat/tests/local_deltacat_storage/exceptions.py, deltacat/tests/test_exceptions.py, deltacat/tests/test_logs.py, deltacat/tests/utils/test_daft.py, deltacat/tests/utils/test_exception_handler.py, deltacat/utils/daft.py, deltacat/utils/pyarrow.py, requirements.txt, setup.py
- This PR addresses few TODOs from #290. 
- Allow configuring the `file_timeout_ms`.
- Allow configuring whether to enable or disable copy by reference.
=> Allow configuring file read timeout and copy of reference

deltacat/__init__.py
=> Deltacat version bump

requirements.txt, setup.py
=> Upgrade daft

deltacat/compute/compactor/model/compact_partition_params.py, deltacat/compute/compactor_v2/compaction_session.py, deltacat/compute/compactor_v2/private/compaction_utils.py, deltacat/compute/compactor_v2/utils/task_options.py, deltacat/tests/compute/compact_partition_rebase_test_cases.py, deltacat/tests/compute/compact_partition_rebase_then_incremental_test_cases.py, deltacat/tests/compute/compact_partition_test_cases.py, deltacat/tests/compute/test_compact_partition_incremental.py, deltacat/tests/compute/test_compact_partition_rebase.py, deltacat/tests/compute/test_compact_partition_rebase_then_incremental.py, deltacat/tests/compute/test_util_common.py
Responding to comments from https://github.com/ray-project/deltacat/pull/333
=> Refactored compaction_session.py

deltacat/__init__.py
Bump DeltaCAT version to 1.1.13
=> Bump DeltaCAT to 1.1.13

deltacat/__init__.py
=> Deltacat version bump to 1.1.14

deltacat/__init__.py
=> Deltacat version bump to 1.1.15

deltacat/logs.py, deltacat/tests/test_logs.py
This PR adds additional context to the json formatter which allows us to log environment variables which can be used to filter right logs.
=> Added context to the json formatter

deltacat/__init__.py
=> Bump version

deltacat/__init__.py, deltacat/exceptions.py
This PR removes the redundant reason from error messages.
=> Remove redundant reason word from the error messages

deltacat/__init__.py, deltacat/io/memcached_object_store.py
Tested on personal stack with num_rounds = 4
=> Clear memcached client cache and bump version

.github/workflows/ci.yml, README.md
Adds CI checks to DeltaCAT 2.0 branch.
Ensure quality of ongoing commits to DeltaCAT 2.0.
Minor updates to GitHub workflow `ci.yml`.
=> Add CI to 2.0 branch.

deltacat/__init__.py
- Patch version bump
- https://github.com/ray-project/deltacat/pull/461
See testing section: https://github.com/ray-project/deltacat/pull/461
=> patch version bump to 1.1.29

deltacat/compute/converter/converter_session.py, deltacat/compute/converter/model/converter_session_params.py, deltacat/compute/converter/pyiceberg/overrides.py, deltacat/compute/converter/pyiceberg/update_snapshot_overrides.py, deltacat/compute/converter/steps/convert.py, deltacat/compute/converter/utils/convert_task_options.py, deltacat/compute/converter/utils/converter_session_utils.py, deltacat/tests/compute/converter/test_convert_session.py
Working version of position delete produced read correctly by Spark SQL select * statement.
Changes:
1. Mainly added support to commit `DELETE` type ManifestContent to Pyiceberg with overrides.
2. Modify the previous test case to make sure the primary key kept are deterministic and aligned with other value columns.
Added unit test case specifically for test Spark read,
Addressed comments for #507.
=> [Converter] Working version of position delete read correctly by Spark

.github/workflows/publish-to-pypi.yml, deltacat/__init__.py
Add init to storage.util folder.
=> fix: add mising storage.util module init

deltacat/catalog/iceberg/impl.py, deltacat/daft/daft_scan.py
fix compatibility issue raised by recent Daft version bump.
- Iceberg e2e read example working: `python -m deltacat.examples.iceberg.iceberg_bucket_writer --warehouse=s3://mingshi-test-andes-local/iceberg/warehouse`
=> chore: fix issue caused due to recent Daft version bump

deltacat/__init__.py
- add missing `__init__` file under `deltacat.daft` module
- bump version for release
=> add missing `__init__` file under `deltacat.daft` module

deltacat/__init__.py, requirements.txt, setup.py
bump deltacat version to 2.0.0b9 so daft version bump to 0.4.13 can be included.
=> bump deltacat version to 2.0.0b9

deltacat/__init__.py
Update the deltacat beta version to `b11`.
=> chore: bump deltacat beta version

deltacat/compute/converter/model/convert_input_files.py, deltacat/compute/converter/pyiceberg/overrides.py, deltacat/compute/converter/steps/convert.py, deltacat/compute/converter/utils/converter_session_utils.py
Code clean up for readability and maintainability by removing nesting structs in converter.
All existing tests passing.
=> [Converter] Code clean up; Remove nested structs

deltacat/compute/converter/converter_session.py, deltacat/compute/converter/model/convert_input.py, deltacat/compute/converter/model/convert_result.py, deltacat/compute/converter/steps/convert.py, deltacat/compute/converter/steps/dedupe.py, deltacat/tests/compute/converter/test_convert_session.py, deltacat/utils/pyarrow.py
This PR includes changes for:
1. Add job run stats for memory fine-tuning
2. Small bug fix in pyarrow writer utils to pass args correctly.
If this is a bugfix, explain how the fix has been tested to ensure the bug is resolved without introducing new issues.
=> [Converter] Add job run stats for memory fine-tuning; bug fix in pyarrow writer utils to pass args correctly

.github/workflows/ci.yml, deltacat/compute/converter/converter_session.py, deltacat/compute/converter/utils/convert_task_options.py, deltacat/compute/converter/utils/converter_session_utils.py, deltacat/tests/compute/converter/test_convert_session.py, deltacat/utils/resources.py
This PR adjust the memory resource estimation for converter() remote tasks based off experiments. Also contains code clean-up regarding determining which snapshot type to commit. 
All existing tests passing.
If this is a bugfix, explain how the fix has been tested to ensure the bug is resolved without introducing new issues.
=> [Converter] Added memory base buffer; Code clean-up

deltacat/compute/converter/converter_session.py, deltacat/compute/converter/pyiceberg/update_snapshot_overrides.py, deltacat/compute/converter/utils/io.py, deltacat/experimental/converter_agent/table_monitor.py, deltacat/tests/compute/converter/test_convert_session.py, deltacat/tests/compute/converter/test_converter_commit_conflict_resolution.py, deltacat/types/tables.py, deltacat/utils/filesystem.py, deltacat/utils/resources.py
In this PR, propose merge conflict resolution for table writes during converter job runs.
During converter job execution, users may initiate concurrent table writes or other operations that commit new snapshots to the Iceberg base table. When the converter attempts to commit its processed results, it encounters a CommitFailedException due to the changed table state. This implementation addresses the conflict resolution strategy to: 1. Enable users to load tables with converter-processed snapshot data, ensuring that new concurrent table writes containing unprocessed data remain isolated and don't interfere with the converter's output view, and 
2. Preserve all concurrent table writes containing new data so that subsequent converter job runs can discover and process this previously …
=> [Converter] Initial Proposal for Conflict Resolution for Table Writes during Converter Job Runs.
